[build]
  command = "vite build"
  publish = "dist/client"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888

[build.environment]
  NETLIFY_USE_DETECTED_FRAMEWORK = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200