/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PurposeRouteImport } from './routes/purpose'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkRccoonRouteImport } from './routes/work/rccoon'
import { Route as WorkEspigaRouteImport } from './routes/work/espiga'
import { Route as WorkCommo2RouteImport } from './routes/work/commo2'
import { Route as BlogPost2RouteImport } from './routes/blog/post-2'
import { Route as BlogPost1RouteImport } from './routes/blog/post-1'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PurposeRoute = PurposeRouteImport.update({
  id: '/purpose',
  path: '/purpose',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRccoonRoute = WorkRccoonRouteImport.update({
  id: '/work/rccoon',
  path: '/work/rccoon',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkEspigaRoute = WorkEspigaRouteImport.update({
  id: '/work/espiga',
  path: '/work/espiga',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkCommo2Route = WorkCommo2RouteImport.update({
  id: '/work/commo2',
  path: '/work/commo2',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPost2Route = BlogPost2RouteImport.update({
  id: '/post-2',
  path: '/post-2',
  getParentRoute: () => BlogRoute,
} as any)
const BlogPost1Route = BlogPost1RouteImport.update({
  id: '/post-1',
  path: '/post-1',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/purpose': typeof PurposeRoute
  '/resume': typeof ResumeRoute
  '/blog/post-1': typeof BlogPost1Route
  '/blog/post-2': typeof BlogPost2Route
  '/work/commo2': typeof WorkCommo2Route
  '/work/espiga': typeof WorkEspigaRoute
  '/work/rccoon': typeof WorkRccoonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/purpose': typeof PurposeRoute
  '/resume': typeof ResumeRoute
  '/blog/post-1': typeof BlogPost1Route
  '/blog/post-2': typeof BlogPost2Route
  '/work/commo2': typeof WorkCommo2Route
  '/work/espiga': typeof WorkEspigaRoute
  '/work/rccoon': typeof WorkRccoonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/purpose': typeof PurposeRoute
  '/resume': typeof ResumeRoute
  '/blog/post-1': typeof BlogPost1Route
  '/blog/post-2': typeof BlogPost2Route
  '/work/commo2': typeof WorkCommo2Route
  '/work/espiga': typeof WorkEspigaRoute
  '/work/rccoon': typeof WorkRccoonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/purpose'
    | '/resume'
    | '/blog/post-1'
    | '/blog/post-2'
    | '/work/commo2'
    | '/work/espiga'
    | '/work/rccoon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/purpose'
    | '/resume'
    | '/blog/post-1'
    | '/blog/post-2'
    | '/work/commo2'
    | '/work/espiga'
    | '/work/rccoon'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/projects'
    | '/purpose'
    | '/resume'
    | '/blog/post-1'
    | '/blog/post-2'
    | '/work/commo2'
    | '/work/espiga'
    | '/work/rccoon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  PurposeRoute: typeof PurposeRoute
  ResumeRoute: typeof ResumeRoute
  WorkCommo2Route: typeof WorkCommo2Route
  WorkEspigaRoute: typeof WorkEspigaRoute
  WorkRccoonRoute: typeof WorkRccoonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purpose': {
      id: '/purpose'
      path: '/purpose'
      fullPath: '/purpose'
      preLoaderRoute: typeof PurposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/rccoon': {
      id: '/work/rccoon'
      path: '/work/rccoon'
      fullPath: '/work/rccoon'
      preLoaderRoute: typeof WorkRccoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/espiga': {
      id: '/work/espiga'
      path: '/work/espiga'
      fullPath: '/work/espiga'
      preLoaderRoute: typeof WorkEspigaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/commo2': {
      id: '/work/commo2'
      path: '/work/commo2'
      fullPath: '/work/commo2'
      preLoaderRoute: typeof WorkCommo2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/post-2': {
      id: '/blog/post-2'
      path: '/post-2'
      fullPath: '/blog/post-2'
      preLoaderRoute: typeof BlogPost2RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/post-1': {
      id: '/blog/post-1'
      path: '/post-1'
      fullPath: '/blog/post-1'
      preLoaderRoute: typeof BlogPost1RouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogPost1Route: typeof BlogPost1Route
  BlogPost2Route: typeof BlogPost2Route
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogPost1Route: BlogPost1Route,
  BlogPost2Route: BlogPost2Route,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  PurposeRoute: PurposeRoute,
  ResumeRoute: ResumeRoute,
  WorkCommo2Route: WorkCommo2Route,
  WorkEspigaRoute: WorkEspigaRoute,
  WorkRccoonRoute: WorkRccoonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
